### POST request to ping
POST http://127.0.0.1:8080/Server/ping
Content-Type: application/json

{
  "UID": "8aacc426020340929fa62fadfd841333",
  "IP": "192.168.0.1",
  "HostName": "Барсик-ПК",
  "Subdivision": "Дом",
  "Domain": "ee",
  "Workgroup": "workspace"
}
###